# Generated by Django 5.0.6 on 2024-07-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('CategoryName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CategoryId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductName', models.CharField(max_length=100)),
                ('ProductId', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductPrice', models.IntegerField()),
                ('ProductDate', models.DateField()),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
